import { 
  Article, 
  SubstackNote, 
  TrafficSourceItem, 
  SMMDiagnostic,
  TimeSeriesPoint 
} from './types';

export const MOCK_ARTICLES: Article[] = [
  {
    "id": "art-212972059",
    "title": "Millions of Barrels Are Still Getting Out of Hormuz. Here's the Catch.",
    "publishDate": "2026-08-27",
    "views": 201,
    "subscribersGained": 4,
    "conversionRate": 1.95,
    "topic": "Geopolitics",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "A ship-to-ship relay off Oman is moving real oil around the blockade. The catch: a shuttle fleet must cross Hormuz twice per cargo – and Iran and Washington are both squeezing it now.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 2
  },
  {
    "id": "art-212292339",
    "title": "Refiners Re-Cut the Barrel. They Did Not Enlarge It.",
    "publishDate": "2026-08-22",
    "views": 188,
    "subscribersGained": 4,
    "conversionRate": 2.05,
    "topic": "Oil",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "Middle East jet-fuel output ran 640,000 b/d below February from March to June. Refiners elsewhere made up the volume by lifting jet yields. Diesel now outbids jet fuel for those molecules.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 3,
    "comments": 0
  },
  {
    "id": "art-211300130",
    "title": "Permission Moves in a Day. Plant Moves in Years.",
    "publishDate": "2026-08-15",
    "views": 226,
    "subscribersGained": 6,
    "conversionRate": 2.75,
    "topic": "Markets",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "The UAE stopped taking an OPEC quota on May 1. Crude output rose. The next increment of gas processing and fractionation capacity is at investment decision, not in service.",
    "baselinePerformance": "+110% vs average signup velocity",
    "smmAdvice": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "frictionPoint": "Minimal friction detected. High reader intent.",
    "futureAction": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "ctaStrategy": "Use an inline \"Subscribe for Institutional Commodity Intelligence\" block placed right after the second analytical chart.",
    "likes": 5,
    "comments": 2
  },
  {
    "id": "art-210734171",
    "title": "The Mine Has Ore. The Plant Still Needs Acid.",
    "publishDate": "2026-08-11",
    "views": 205,
    "subscribersGained": 4,
    "conversionRate": 1.95,
    "topic": "Hard Assets",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "Hormuz turned an already-tight sulfur market acute, and that shock reached an Indonesian nickel plant. The outcome depended on the flowsheet and reagent position, not the metal.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-210029640",
    "title": "A Declaration Is Not Cover.",
    "publishDate": "2026-08-06",
    "views": 221,
    "subscribersGained": 6,
    "conversionRate": 2.5,
    "topic": "Markets",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "Riyadh pledged protection over Bab el-Mandeb, then founded an alliance. Underwriters wrote covenants anyway. The only publicly explained crossings ran on Houthi clearance.",
    "baselinePerformance": "+100% vs average signup velocity",
    "smmAdvice": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "frictionPoint": "Low comment section participation relative to views (221). Readers saved the piece but did not debate inside Substack.",
    "futureAction": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "ctaStrategy": "Use an inline \"Subscribe for Institutional Commodity Intelligence\" block placed right after the second analytical chart.",
    "likes": 6,
    "comments": 0
  },
  {
    "id": "art-208820989",
    "title": "Three Negotiations. None of Them With Russia.",
    "publishDate": "2026-07-30",
    "views": 178,
    "subscribersGained": 4,
    "conversionRate": 2.15,
    "topic": "Geopolitics",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "The EU held the Russian oil cap at $44.10 rather than let its formula lift it to $58, and shielded a specialist Greek LNG fleet. Both were settled among Europeans, not with Moscow.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 1,
    "comments": 0
  },
  {
    "id": "art-208181574",
    "title": "The Market Survived on Stored Barrels. The Next One Is a Choice.",
    "publishDate": "2026-07-23",
    "views": 202,
    "subscribersGained": 3,
    "conversionRate": 1.5,
    "topic": "Oil",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "Emergency reserves became recurring supply, not just reassurance. Most of the first authorised release is already drawn. The next stabilising barrel is political, not automatic.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 3
  },
  {
    "id": "art-207896371",
    "title": "Leaving the Strait Is Capacity. Reaching the Buyer Is Resilience.",
    "publishDate": "2026-07-21",
    "views": 227,
    "subscribersGained": 5,
    "conversionRate": 2.35,
    "topic": "Geopolitics",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "The Gulf's routes around Hormuz keep crude flowing — but Fujairah loads into open water, Yanbu escapes one strait into another, and Qatari LNG has no way around it at all.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 3
  },
  {
    "id": "art-207534278",
    "title": "The Barrels Left the Quota. Not the Market.",
    "publishDate": "2026-07-18",
    "views": 175,
    "subscribersGained": 4,
    "conversionRate": 2.3,
    "topic": "Oil",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "The UAE quit OPEC+ on May 1. Its crude did not leave the market — it left the system the alliance uses to restrain supply. OPEC+ can still cut. It cannot discipline Abu Dhabi from inside.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-207267797",
    "title": "The Strait Was Passable. For LNG, That Wasn’t Enough.",
    "publishDate": "2026-07-16",
    "views": 218,
    "subscribersGained": 5,
    "conversionRate": 2.1,
    "topic": "Geopolitics",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "An LNG carrier was struck July 7. Three Qatari ships turned back, and no LNG carrier has crossed since July 11 while other cargo kept moving. A passable Strait, a stalled LNG chain.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 6,
    "comments": 2
  },
  {
    "id": "art-206998467",
    "title": "Announced Gigawatts Are Not Operating Gigawatts.",
    "publishDate": "2026-07-14",
    "views": 206,
    "subscribersGained": 5,
    "conversionRate": 2.35,
    "topic": "AI",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "A one-gigawatt AI campus in Alberta rests on three power layers — a supply contract, a grid allocation, a gas plant years from starting. The headline number is not the deliverable one.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming AI articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming AI articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-206433443",
    "title": "The Crisis Came Through Oil. Gold Priced It as Rates.",
    "publishDate": "2026-07-10",
    "views": 197,
    "subscribersGained": 5,
    "conversionRate": 2.45,
    "topic": "Oil",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "A renewed Iran shock sent oil up more than 5%. That should have lifted gold. It fell nearly 2% as yields and the dollar rose — the tape priced the shock through rates first, not fear.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 3,
    "comments": 0
  },
  {
    "id": "art-206058910",
    "title": "Oil Flinched First. The Bond Market Flinched Too.",
    "publishDate": "2026-07-08",
    "views": 171,
    "subscribersGained": 2,
    "conversionRate": 1.35,
    "topic": "Oil",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "JMIC confirmed three tanker attacks on July 7. OFAC revoked Iran's oil license hours later. Crude moved first — then the 30-year Treasury yield cleared 5% and breakevens ticked higher too.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 200+ institutional macro allocators receiving our private updates.\"",
    "likes": 1,
    "comments": 0
  },
  {
    "id": "art-205206330",
    "title": "A Smaller Ticket. The Same Barrel.",
    "publishDate": "2026-07-05",
    "views": 204,
    "subscribersGained": 4,
    "conversionRate": 2.2,
    "topic": "Oil",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "CME's new 10-barrel WTI contract is slated for launch on August 30. The crude market underneath it hasn't gotten any easier to trade — only the ticket to bet on it has.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 4,
    "comments": 2
  },
  {
    "id": "art-204396670",
    "title": "Central Banks Kept Buying. Gold Fell Anyway.",
    "publishDate": "2026-07-01",
    "views": 154,
    "subscribersGained": 4,
    "conversionRate": 2.3,
    "topic": "Hard Assets",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "Gold had its worst quarter since 2013 while surveyed central banks expected official reserves to keep rising. Both are true. Reserve demand and the traded price run on different clocks.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-203969094",
    "title": "Hormuz Didn't Reopen. The Tollbooth Moved.",
    "publishDate": "2026-06-28",
    "views": 253,
    "subscribersGained": 5,
    "conversionRate": 1.8,
    "topic": "Geopolitics",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "The Strait went from closed to argued over. Iran is selling permission. Oman is denying tolls in public and pricing services in private. Hormuz is physically open in places — and priced as if it isn't",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 4,
    "comments": 0
  },
  {
    "id": "art-203392714",
    "title": "The Mine Is Not the Supply",
    "publishDate": "2026-06-26",
    "views": 171,
    "subscribersGained": 3,
    "conversionRate": 1.9,
    "topic": "Hard Assets",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "The DRC replaced its export ban with a quota. The cobalt market is now quoting two prices: the old glut and the new access.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-202686929",
    "title": "The Vault Is the Variable",
    "publishDate": "2026-06-19",
    "views": 166,
    "subscribersGained": 4,
    "conversionRate": 2.3,
    "topic": "Hard Assets",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "Central Banks are repatriating gold,diversifying where it sits, and in some cases mobilizing it under stress. The direction of the flow stopped being the signal. The sovereign's constraint always was.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-202609281",
    "title": "The Rate Didn't Move. The Path Did.",
    "publishDate": "2026-06-18",
    "views": 148,
    "subscribersGained": 2,
    "conversionRate": 1.2,
    "topic": "Macro",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "The Fed held at 3.5–3.75%. But the projected path moved higher, forward guidance disappeared from the statement, and markets had to price a less comfortable future.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 200+ institutional macro allocators receiving our private updates.\"",
    "likes": 0,
    "comments": 0
  },
  {
    "id": "art-200991664",
    "title": "Who Pays When Crude Goes Up?",
    "publishDate": "2026-06-07",
    "views": 205,
    "subscribersGained": 5,
    "conversionRate": 2.35,
    "topic": "Oil",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "The first wave was oil. The second wave was rates. The third wave is in the country tier — and the FX screen is showing it before the credit ratings do.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 2
  },
  {
    "id": "art-199858931",
    "title": "Second Wave. Different Barrel.",
    "publishDate": "2026-05-30",
    "views": 201,
    "subscribersGained": 6,
    "conversionRate": 2.9,
    "topic": "Oil",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "The first wave was oil. The second wave is rates. The cross-asset map has split — and the dispersion within it tells you where the next move is.",
    "baselinePerformance": "+116% vs average signup velocity",
    "smmAdvice": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "frictionPoint": "Minimal friction detected. High reader intent.",
    "futureAction": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "ctaStrategy": "Use an inline \"Subscribe for Institutional Commodity Intelligence\" block placed right after the second analytical chart.",
    "likes": 6,
    "comments": 2
  },
  {
    "id": "art-199729795",
    "title": "The toll booth is still operational",
    "publishDate": "2026-05-29",
    "views": 138,
    "subscribersGained": 2,
    "conversionRate": 1.35,
    "topic": "Geopolitics",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "Even as attacks and counter-strikes escalate, one fact remains unchanged:",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 200+ institutional macro allocators receiving our private updates.\"",
    "likes": 1,
    "comments": 0
  },
  {
    "id": "art-198939442",
    "title": "The Toll Booth at the Mouth of the World",
    "publishDate": "2026-05-23",
    "views": 150,
    "subscribersGained": 3,
    "conversionRate": 1.9,
    "topic": "Geopolitics",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "Iran built a chokepoint authority. The US tried to escort its way around it. The Saudis declined to help. The scorecard is still 0 out of 5",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-198914118",
    "title": "The Toll Booth at the Mouth of the World",
    "publishDate": "2026-05-23",
    "views": 235,
    "subscribersGained": 6,
    "conversionRate": 2.45,
    "topic": "Geopolitics",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "Iran built a chokepoint authority. The US tried to escort its way around it. The Saudis declined to help. The scorecard is still 0 out of 5.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 3,
    "comments": 0
  },
  {
    "id": "art-197301647",
    "title": "PSI Capital crossed 100 subscribers on Substack in our first month- Thank you",
    "publishDate": "2026-05-12",
    "views": 165,
    "subscribersGained": 3,
    "conversionRate": 1.95,
    "topic": "Markets",
    "CTAtype": "Subscribe",
    "format": "Scorecard",
    "thesis": "When we started, the goal was simple: build a clearer way to think about how macro and geopolitics flow through commodities, prices, and industries.Thanks for reading PSI Capital's Substack!",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-197088652",
    "title": "The Invoice Has Left the Barrel",
    "publishDate": "2026-05-10",
    "views": 228,
    "subscribersGained": 6,
    "conversionRate": 2.65,
    "topic": "Oil",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "Four notes. One framework. Oil is staying firm — and the bill is already moving through the system.",
    "baselinePerformance": "+106% vs average signup velocity",
    "smmAdvice": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "frictionPoint": "Minimal friction detected. High reader intent.",
    "futureAction": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "ctaStrategy": "Use an inline \"Subscribe for Institutional Commodity Intelligence\" block placed right after the second analytical chart.",
    "likes": 7,
    "comments": 7
  },
  {
    "id": "art-196102130",
    "title": "Who Pays for $110-120 Oil?",
    "publishDate": "2026-05-01",
    "views": 210,
    "subscribersGained": 6,
    "conversionRate": 2.75,
    "topic": "Oil",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "The barrel is where the shock starts. The balance sheet is where it becomes a regime.",
    "baselinePerformance": "+110% vs average signup velocity",
    "smmAdvice": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "frictionPoint": "Low comment section participation relative to views (210). Readers saved the piece but did not debate inside Substack.",
    "futureAction": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "ctaStrategy": "Use an inline \"Subscribe for Institutional Commodity Intelligence\" block placed right after the second analytical chart.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-195332390",
    "title": "The Market Is Still Counting Spare It Cannot Actually Use",
    "publishDate": "2026-04-24",
    "views": 193,
    "subscribersGained": 4,
    "conversionRate": 1.95,
    "topic": "Markets",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "Last week's plunge into the mid-$80s was a misread. The cushion is smaller than the market still wants to believe. This article is Part 1 in this series",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-194532864",
    "title": "The Talks Came Back. The System Still Didn’t.",
    "publishDate": "2026-04-17",
    "views": 217,
    "subscribersGained": 7,
    "conversionRate": 3.1,
    "topic": "Markets",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "The market keeps pricing relief before the corridor proves it should. Three headlines in ten days. The same mismatch every time.",
    "baselinePerformance": "+124% vs average signup velocity",
    "smmAdvice": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "frictionPoint": "Minimal friction detected. High reader intent.",
    "futureAction": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "ctaStrategy": "Use an inline \"Subscribe for Institutional Commodity Intelligence\" block placed right after the second analytical chart.",
    "likes": 10,
    "comments": 4
  },
  {
    "id": "art-193936421",
    "title": "The Market Priced Peace. The Oil System Didn’t.",
    "publishDate": "2026-04-12",
    "views": 190,
    "subscribersGained": 5,
    "conversionRate": 2.75,
    "topic": "Oil",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "A ceasefire removed immediate panic. It did not restore the route, the insurers, the operators, or the physical market underneath it.",
    "baselinePerformance": "+110% vs average signup velocity",
    "smmAdvice": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "frictionPoint": "Low comment section participation relative to views (190). Readers saved the piece but did not debate inside Substack.",
    "futureAction": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "ctaStrategy": "Use an inline \"Subscribe for Institutional Commodity Intelligence\" block placed right after the second analytical chart.",
    "likes": 5,
    "comments": 1
  }
];

export const MOCK_NOTES: SubstackNote[] = [
  {
    "id": "note-324233258",
    "hook": "The roadstead has room. The constraint is narrower: how many owners will keep sending a shuttle across Hormuz, again and again, wh...",
    "publishDate": "2026-08-29",
    "impressions": 159,
    "likes": 4,
    "restacks": 2,
    "replies": 0,
    "profileClicks": 8,
    "subscribersGained": 1,
    "format": "Chart",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 8 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-324232985",
    "hook": "Watch the transfer zone and the system looks busy. Watch which hull crosses Hormuz and which doesn't, and the picture changes.  On...",
    "publishDate": "2026-08-28",
    "impressions": 135,
    "likes": 5,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 9,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 9 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-324232726",
    "hook": "A large number of barrels sitting in ship-to-ship pairs is not the same as a restored daily flow through the Strait. Stock in tran...",
    "publishDate": "2026-08-28",
    "impressions": 123,
    "likes": 4,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 10,
    "subscribersGained": 1,
    "format": "Chart",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-323702181",
    "hook": "Millions of barrels are still leaving Hormuz. That sentence is true. It is also incomplete. The catch is not whether oil is moving...",
    "publishDate": "2026-08-27",
    "impressions": 177,
    "likes": 7,
    "restacks": 1,
    "replies": 0,
    "profileClicks": 17,
    "subscribersGained": 2,
    "format": "Text",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 17 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-323667919",
    "hook": "Later today: our read on the Hormuz STS relay. The transfer zone has room. The shuttle fleet is what's being squeezed — by Iran on...",
    "publishDate": "2026-08-27",
    "impressions": 123,
    "likes": 4,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 6,
    "subscribersGained": 1,
    "format": "Text",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-323583425",
    "hook": "The CFTC extended the review period of CME’s 10 barrel WTI contract through to October 26, 2026 for the same concerns we had expre...",
    "publishDate": "2026-08-27",
    "impressions": 119,
    "likes": 3,
    "restacks": 0,
    "replies": 1,
    "profileClicks": 8,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-212292339",
    "topic": "Oil",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-323235591",
    "hook": "If you want to understand how the catastrophe in Nepal could have happened, I published an article a month ago about how rivers an...",
    "publishDate": "2026-08-26",
    "impressions": 173,
    "likes": 6,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 14,
    "subscribersGained": 2,
    "format": "Chart",
    "linkedArticleId": "art-211300130",
    "topic": "Markets",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 14 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-322878081",
    "hook": "Iran’s Army is now claiming a wider control zone, not just the Strait.  It says vessels are under surveillance hundreds of kilomet...",
    "publishDate": "2026-08-26",
    "impressions": 129,
    "likes": 3,
    "restacks": 1,
    "replies": 0,
    "profileClicks": 12,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-322333133",
    "hook": "Ship operators face two sets of instructions that do not resolve into one workable rule. Iran has struck vessels that left its des...",
    "publishDate": "2026-08-25",
    "impressions": 161,
    "likes": 5,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 8,
    "subscribersGained": 1,
    "format": "Chart",
    "linkedArticleId": "art-211300130",
    "topic": "Markets",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 8 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-322149592",
    "hook": "The U.S. Treasury is now warning that sailors and shipping companies can risk sanctions or penalties simply by responding to infor...",
    "publishDate": "2026-08-25",
    "impressions": 125,
    "likes": 2,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 8,
    "subscribersGained": 1,
    "format": "Text",
    "linkedArticleId": "art-206998467",
    "topic": "AI",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-322043197",
    "hook": "One source this week claimed the U.S. has only 41 days of crude left — the lowest cover in half a century.  That figure folds comm...",
    "publishDate": "2026-08-25",
    "impressions": 111,
    "likes": 3,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 9,
    "subscribersGained": 1,
    "format": "Chart",
    "linkedArticleId": "art-212292339",
    "topic": "Oil",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-321644418",
    "hook": "The problem is that lower long-term yields are not a free lunch. If Treasury pushes them down through buybacks while deficits rema...",
    "publishDate": "2026-08-24",
    "impressions": 155,
    "likes": 6,
    "restacks": 0,
    "replies": 1,
    "profileClicks": 15,
    "subscribersGained": 2,
    "format": "Text",
    "linkedArticleId": "art-202609281",
    "topic": "Macro",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 15 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-321349458",
    "hook": "FT reports that Saudi Arabia is evaluating state-backed war insurance as private cover costs remain elevated.  State-backed cover ...",
    "publishDate": "2026-08-24",
    "impressions": 213,
    "likes": 10,
    "restacks": 1,
    "replies": 0,
    "profileClicks": 11,
    "subscribersGained": 1,
    "format": "Text",
    "linkedArticleId": "art-206998467",
    "topic": "AI",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 11 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-321490576",
    "hook": "The system is reoptimizing, but by creating scarcity somewhere else rather than absorbing the shock. We wrote about this: “For any...",
    "publishDate": "2026-08-24",
    "impressions": 123,
    "likes": 4,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 8,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-211300130",
    "topic": "Markets",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-321353394",
    "hook": "Headlines moved fast: Buffalo Niagara International Airport out of fuel, unable to refuel aircraft, NOTAM issued. Many reactions t...",
    "publishDate": "2026-08-24",
    "impressions": 137,
    "likes": 3,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 11,
    "subscribersGained": 1,
    "format": "Chart",
    "linkedArticleId": "art-206998467",
    "topic": "AI",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-321344037",
    "hook": "An excellent point:",
    "publishDate": "2026-08-24",
    "impressions": 99,
    "likes": 2,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 9,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-211300130",
    "topic": "Markets",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-321343074",
    "hook": "Iran is building a formal blacklist for ships that break its prescribed transit rules in the Strait of Hormuz. Non-compliant vesse...",
    "publishDate": "2026-08-24",
    "impressions": 137,
    "likes": 3,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 7,
    "subscribersGained": 1,
    "format": "Text",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-320689338",
    "hook": "Most of the replacement jet fuel came from a yield decision, not from new capacity. We explain why:",
    "publishDate": "2026-08-23",
    "impressions": 111,
    "likes": 3,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 7,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-212292339",
    "topic": "Oil",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-320281056",
    "hook": "The jet-fuel emergency has closed as a shortage story. It has reopened as an allocation one.  We explain why:",
    "publishDate": "2026-08-22",
    "impressions": 195,
    "likes": 7,
    "restacks": 2,
    "replies": 0,
    "profileClicks": 16,
    "subscribersGained": 2,
    "format": "Chart",
    "linkedArticleId": "art-212292339",
    "topic": "Oil",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 16 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-320130842",
    "hook": "Iran has granted special permission for a number of Iraqi oil tankers to transit the Strait of Hormuz — after repeated requests fr...",
    "publishDate": "2026-08-22",
    "impressions": 129,
    "likes": 3,
    "restacks": 1,
    "replies": 0,
    "profileClicks": 12,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  }
];

export const MOCK_SMM_DIAGNOSTICS: SMMDiagnostic[] = [
  {
    "id": "diag-art-1",
    "contentTitle": "Millions of Barrels Are Still Getting Out of Hormuz. Here's the Catch.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 201 views. Conversion rate sits at 1.95%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "201 Views | 1.95% Conv."
  },
  {
    "id": "diag-art-2",
    "contentTitle": "Refiners Re-Cut the Barrel. They Did Not Enlarge It.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 188 views. Conversion rate sits at 2.05%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "188 Views | 2.05% Conv."
  },
  {
    "id": "diag-art-3",
    "contentTitle": "Permission Moves in a Day. Plant Moves in Years.",
    "contentType": "Article",
    "diagnosticType": "High Conversion",
    "articleType": "Essay",
    "topic": "Markets",
    "theWhy": "Steady engagement with 226 views. Conversion rate sits at 2.75%.",
    "frictionPoint": "Minimal friction detected. High reader intent.",
    "futureAction": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "metricHighlight": "226 Views | 2.75% Conv."
  },
  {
    "id": "diag-art-4",
    "contentTitle": "The Mine Has Ore. The Plant Still Needs Acid.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Hard Assets",
    "theWhy": "Steady engagement with 205 views. Conversion rate sits at 1.95%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "205 Views | 1.95% Conv."
  },
  {
    "id": "diag-art-5",
    "contentTitle": "A Declaration Is Not Cover.",
    "contentType": "Article",
    "diagnosticType": "High Conversion",
    "articleType": "Essay",
    "topic": "Markets",
    "theWhy": "Steady engagement with 221 views. Conversion rate sits at 2.5%.",
    "frictionPoint": "Low comment section participation relative to views (221). Readers saved the piece but did not debate inside Substack.",
    "futureAction": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "metricHighlight": "221 Views | 2.5% Conv."
  },
  {
    "id": "diag-art-6",
    "contentTitle": "Three Negotiations. None of Them With Russia.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 178 views. Conversion rate sits at 2.15%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "178 Views | 2.15% Conv."
  },
  {
    "id": "diag-art-7",
    "contentTitle": "The Market Survived on Stored Barrels. The Next One Is a Choice.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 202 views. Conversion rate sits at 1.5%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "202 Views | 1.5% Conv."
  },
  {
    "id": "diag-art-8",
    "contentTitle": "Leaving the Strait Is Capacity. Reaching the Buyer Is Resilience.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 227 views. Conversion rate sits at 2.35%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "227 Views | 2.35% Conv."
  },
  {
    "id": "diag-art-9",
    "contentTitle": "The Barrels Left the Quota. Not the Market.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 175 views. Conversion rate sits at 2.3%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "175 Views | 2.3% Conv."
  },
  {
    "id": "diag-art-10",
    "contentTitle": "The Strait Was Passable. For LNG, That Wasn’t Enough.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 218 views. Conversion rate sits at 2.1%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "218 Views | 2.1% Conv."
  },
  {
    "id": "diag-art-11",
    "contentTitle": "Announced Gigawatts Are Not Operating Gigawatts.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "AI",
    "theWhy": "Steady engagement with 206 views. Conversion rate sits at 2.35%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming AI articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "206 Views | 2.35% Conv."
  },
  {
    "id": "diag-art-12",
    "contentTitle": "The Crisis Came Through Oil. Gold Priced It as Rates.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 197 views. Conversion rate sits at 2.45%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "197 Views | 2.45% Conv."
  },
  {
    "id": "diag-art-13",
    "contentTitle": "Oil Flinched First. The Bond Market Flinched Too.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 171 views. Conversion rate sits at 1.35%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "171 Views | 1.35% Conv."
  },
  {
    "id": "diag-art-14",
    "contentTitle": "A Smaller Ticket. The Same Barrel.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 204 views. Conversion rate sits at 2.2%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "204 Views | 2.2% Conv."
  },
  {
    "id": "diag-art-15",
    "contentTitle": "Central Banks Kept Buying. Gold Fell Anyway.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Hard Assets",
    "theWhy": "Steady engagement with 154 views. Conversion rate sits at 2.3%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "154 Views | 2.3% Conv."
  },
  {
    "id": "diag-art-16",
    "contentTitle": "Hormuz Didn't Reopen. The Tollbooth Moved.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 253 views. Conversion rate sits at 1.8%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "253 Views | 1.8% Conv."
  },
  {
    "id": "diag-art-17",
    "contentTitle": "The Mine Is Not the Supply",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Hard Assets",
    "theWhy": "Steady engagement with 171 views. Conversion rate sits at 1.9%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "171 Views | 1.9% Conv."
  },
  {
    "id": "diag-art-18",
    "contentTitle": "The Vault Is the Variable",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Hard Assets",
    "theWhy": "Steady engagement with 166 views. Conversion rate sits at 2.3%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "166 Views | 2.3% Conv."
  },
  {
    "id": "diag-art-19",
    "contentTitle": "The Rate Didn't Move. The Path Did.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Macro",
    "theWhy": "Steady engagement with 148 views. Conversion rate sits at 1.2%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "148 Views | 1.2% Conv."
  },
  {
    "id": "diag-art-20",
    "contentTitle": "Who Pays When Crude Goes Up?",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 205 views. Conversion rate sits at 2.35%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "205 Views | 2.35% Conv."
  },
  {
    "id": "diag-art-21",
    "contentTitle": "Second Wave. Different Barrel.",
    "contentType": "Article",
    "diagnosticType": "High Conversion",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 201 views. Conversion rate sits at 2.9%.",
    "frictionPoint": "Minimal friction detected. High reader intent.",
    "futureAction": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "metricHighlight": "201 Views | 2.9% Conv."
  },
  {
    "id": "diag-art-22",
    "contentTitle": "The toll booth is still operational",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 138 views. Conversion rate sits at 1.35%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "138 Views | 1.35% Conv."
  },
  {
    "id": "diag-art-23",
    "contentTitle": "The Toll Booth at the Mouth of the World",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 150 views. Conversion rate sits at 1.9%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "150 Views | 1.9% Conv."
  },
  {
    "id": "diag-art-24",
    "contentTitle": "The Toll Booth at the Mouth of the World",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 235 views. Conversion rate sits at 2.45%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "235 Views | 2.45% Conv."
  },
  {
    "id": "diag-art-25",
    "contentTitle": "PSI Capital crossed 100 subscribers on Substack in our first month- Thank you",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Scorecard",
    "topic": "Markets",
    "theWhy": "Steady engagement with 165 views. Conversion rate sits at 1.95%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "165 Views | 1.95% Conv."
  },
  {
    "id": "diag-art-26",
    "contentTitle": "The Invoice Has Left the Barrel",
    "contentType": "Article",
    "diagnosticType": "High Conversion",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 228 views. Conversion rate sits at 2.65%.",
    "frictionPoint": "Minimal friction detected. High reader intent.",
    "futureAction": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "metricHighlight": "228 Views | 2.65% Conv."
  },
  {
    "id": "diag-art-27",
    "contentTitle": "Who Pays for $110-120 Oil?",
    "contentType": "Article",
    "diagnosticType": "High Conversion",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 210 views. Conversion rate sits at 2.75%.",
    "frictionPoint": "Low comment section participation relative to views (210). Readers saved the piece but did not debate inside Substack.",
    "futureAction": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "metricHighlight": "210 Views | 2.75% Conv."
  },
  {
    "id": "diag-art-28",
    "contentTitle": "The Market Is Still Counting Spare It Cannot Actually Use",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Markets",
    "theWhy": "Steady engagement with 193 views. Conversion rate sits at 1.95%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "193 Views | 1.95% Conv."
  },
  {
    "id": "diag-art-29",
    "contentTitle": "The Talks Came Back. The System Still Didn’t.",
    "contentType": "Article",
    "diagnosticType": "High Conversion",
    "articleType": "Essay",
    "topic": "Markets",
    "theWhy": "Steady engagement with 217 views. Conversion rate sits at 3.1%.",
    "frictionPoint": "Minimal friction detected. High reader intent.",
    "futureAction": "For your next Markets essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "metricHighlight": "217 Views | 3.1% Conv."
  },
  {
    "id": "diag-art-30",
    "contentTitle": "The Market Priced Peace. The Oil System Didn’t.",
    "contentType": "Article",
    "diagnosticType": "High Conversion",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 190 views. Conversion rate sits at 2.75%.",
    "frictionPoint": "Low comment section participation relative to views (190). Readers saved the piece but did not debate inside Substack.",
    "futureAction": "For your next Oil essay: Pin this piece in your welcome sequence, and post a 2-part Note teaser sequence containing the primary thesis graphic at 8:00 AM EST on publication day.",
    "metricHighlight": "190 Views | 2.75% Conv."
  },
  {
    "id": "diag-note-1",
    "contentTitle": "Note: \"The roadstead has room. The constraint is narrower...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Chart",
    "topic": "Geopolitics",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 8 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 5.0% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "4 Likes | 2 Restacks"
  },
  {
    "id": "diag-note-2",
    "contentTitle": "Note: \"Watch the transfer zone and the system looks busy....\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Image",
    "topic": "Geopolitics",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 9 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 6.7% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "5 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-3",
    "contentTitle": "Note: \"A large number of barrels sitting in ship-to-ship ...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Chart",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 8.1% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "4 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-4",
    "contentTitle": "Note: \"Millions of barrels are still leaving Hormuz. That...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Text",
    "topic": "Geopolitics",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 17 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 9.6% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "7 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-5",
    "contentTitle": "Note: \"Later today: our read on the Hormuz STS relay. The...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Text",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 4.9% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "4 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-6",
    "contentTitle": "Note: \"The CFTC extended the review period of CME’s 10 ba...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Oil",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 6.7% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-7",
    "contentTitle": "Note: \"If you want to understand how the catastrophe in N...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Chart",
    "topic": "Markets",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 14 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 8.1% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "6 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-8",
    "contentTitle": "Note: \"Iran’s Army is now claiming a wider control zone, ...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 9.3% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-9",
    "contentTitle": "Note: \"Ship operators face two sets of instructions that ...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Chart",
    "topic": "Markets",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 8 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 5.0% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "5 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-10",
    "contentTitle": "Note: \"The U.S. Treasury is now warning that sailors and ...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Text",
    "topic": "AI",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 6.4% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "2 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-11",
    "contentTitle": "Note: \"One source this week claimed the U.S. has only 41 ...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Chart",
    "topic": "Oil",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 8.1% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-12",
    "contentTitle": "Note: \"The problem is that lower long-term yields are not...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Text",
    "topic": "Macro",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 15 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 9.7% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "6 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-13",
    "contentTitle": "Note: \"FT reports that Saudi Arabia is evaluating state-b...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Text",
    "topic": "AI",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 11 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 5.2% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "10 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-14",
    "contentTitle": "Note: \"The system is reoptimizing, but by creating scarci...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Markets",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 6.5% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "4 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-15",
    "contentTitle": "Note: \"Headlines moved fast: Buffalo Niagara Internationa...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Chart",
    "topic": "AI",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 8.0% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-16",
    "contentTitle": "Note: \"An excellent point:...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Markets",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 9.1% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "2 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-17",
    "contentTitle": "Note: \"Iran is building a formal blacklist for ships that...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Text",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 5.1% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-18",
    "contentTitle": "Note: \"Most of the replacement jet fuel came from a yield...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Oil",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 6.3% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-19",
    "contentTitle": "Note: \"The jet-fuel emergency has closed as a shortage st...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Chart",
    "topic": "Oil",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 16 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 8.2% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "7 Likes | 2 Restacks"
  },
  {
    "id": "diag-note-20",
    "contentTitle": "Note: \"Iran has granted special permission for a number o...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 9.3% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 1 Restacks"
  }
];

export const MOCK_TRAFFIC_SOURCES: TrafficSourceItem[] = [
  {
    id: 'ts-01',
    source: 'Substack App & Recommendations',
    category: 'Substack Internal',
    uniqueVisitors: 1420,
    newSubscribers: 114,
    conversionRate: 8.03,
    qualityClassification: 'High',
    description: 'Readers discovering PSI Capital inside the Substack mobile app feed, recommendation algorithm, and cross-writer suggestions.'
  },
  {
    id: 'ts-02',
    source: 'Twitter / X Shares',
    category: 'Social Media',
    uniqueVisitors: 680,
    newSubscribers: 42,
    conversionRate: 6.18,
    qualityClassification: 'High',
    description: 'Direct clicks from shared article links, quote threads, and market commentary posted on Twitter/X.'
  },
  {
    id: 'ts-03',
    source: 'LinkedIn Posts & Articles',
    category: 'Social Media',
    uniqueVisitors: 340,
    newSubscribers: 28,
    conversionRate: 8.24,
    qualityClassification: 'High',
    description: 'Institutional and executive reader traffic from professional LinkedIn network shares.'
  },
  {
    id: 'ts-04',
    source: 'Google Search / SEO',
    category: 'Organic Search',
    uniqueVisitors: 410,
    newSubscribers: 18,
    conversionRate: 4.39,
    qualityClassification: 'Medium',
    description: 'Organic search traffic landing directly on long-form energy and commodity essays via Google search.'
  },
  {
    id: 'ts-05',
    source: 'Direct / Unattributed',
    category: 'Direct / Unattributed',
    uniqueVisitors: 520,
    newSubscribers: 16,
    conversionRate: 3.08,
    qualityClassification: 'Medium',
    description: 'Direct email app opens, private browser bookmarks, and instant message links where referrers are omitted.'
  }
];

// Authentic subscriber growth curve: 35 (Apr) -> 100 (May milestone) -> 145 (Jun) -> 185 (Jul) -> 218 (Aug Today)
export const MOCK_TIME_SERIES = {
  'Last 7 Days': [
    { date: 'Aug 25', subscribers: 208, organicSubscribers: 2, referralSubscribers: 1 },
    { date: 'Aug 26', subscribers: 210, organicSubscribers: 2, referralSubscribers: 0 },
    { date: 'Aug 27', subscribers: 212, organicSubscribers: 1, referralSubscribers: 1 },
    { date: 'Aug 28', subscribers: 214, organicSubscribers: 2, referralSubscribers: 0 },
    { date: 'Aug 29', subscribers: 215, organicSubscribers: 1, referralSubscribers: 0 },
    { date: 'Aug 30', subscribers: 216, organicSubscribers: 1, referralSubscribers: 0 },
    { date: 'Aug 31', subscribers: 218, organicSubscribers: 2, referralSubscribers: 0 },
  ],
  'Last 30 Days': Array.from({ length: 30 }, (_, i) => {
    const day = i + 1;
    const baseSubs = 182 + Math.floor((i / 29) * 36);
    return {
      date: `Aug ${day}`,
      subscribers: baseSubs,
      organicSubscribers: 1 + (i % 3 === 0 ? 1 : 0),
      referralSubscribers: (i % 5 === 0 ? 1 : 0),
    };
  }),
  'Last 90 Days': [
    { date: 'Wk 1 (Jun)', subscribers: 135, organicSubscribers: 8, referralSubscribers: 3 },
    { date: 'Wk 2 (Jun)', subscribers: 142, organicSubscribers: 7, referralSubscribers: 2 },
    { date: 'Wk 3 (Jun)', subscribers: 150, organicSubscribers: 8, referralSubscribers: 3 },
    { date: 'Wk 4 (Jun)', subscribers: 158, organicSubscribers: 8, referralSubscribers: 2 },
    { date: 'Wk 5 (Jul)', subscribers: 165, organicSubscribers: 7, referralSubscribers: 2 },
    { date: 'Wk 6 (Jul)', subscribers: 172, organicSubscribers: 7, referralSubscribers: 2 },
    { date: 'Wk 7 (Jul)', subscribers: 180, organicSubscribers: 8, referralSubscribers: 3 },
    { date: 'Wk 8 (Jul)', subscribers: 188, organicSubscribers: 8, referralSubscribers: 2 },
    { date: 'Wk 9 (Aug)', subscribers: 196, organicSubscribers: 8, referralSubscribers: 2 },
    { date: 'Wk 10 (Aug)', subscribers: 203, organicSubscribers: 7, referralSubscribers: 2 },
    { date: 'Wk 11 (Aug)', subscribers: 211, organicSubscribers: 8, referralSubscribers: 2 },
    { date: 'Wk 12 (Aug)', subscribers: 218, organicSubscribers: 7, referralSubscribers: 2 },
  ],
  'All-Time': [
    { date: 'Apr 2026', subscribers: 35, organicSubscribers: 28, referralSubscribers: 7 },
    { date: 'May 2026 (100 Subs)', subscribers: 100, organicSubscribers: 52, referralSubscribers: 13 },
    { date: 'Jun 2026', subscribers: 145, organicSubscribers: 36, referralSubscribers: 9 },
    { date: 'Jul 2026', subscribers: 185, organicSubscribers: 32, referralSubscribers: 8 },
    { date: 'Aug 2026', subscribers: 218, organicSubscribers: 26, referralSubscribers: 7 },
  ]
};
