import { 
  Article, 
  SubstackNote, 
  TrafficSourceItem, 
  SMMDiagnostic,
  TimeSeriesPoint 
} from './types';

export const MOCK_ARTICLES: Article[] = [
  {
    "id": "art-212972059",
    "title": "Millions of Barrels Are Still Getting Out of Hormuz. Here's the Catch.",
    "publishDate": "2026-08-27",
    "views": 480,
    "subscribersGained": 5,
    "conversionRate": 0.97,
    "topic": "Geopolitics",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "A ship-to-ship relay off Oman is moving real oil around the blockade. The catch: a shuttle fleet must cross Hormuz twice per cargo – and Iran and Washington are both squeezing it now.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 5,
    "comments": 2
  },
  {
    "id": "art-212292339",
    "title": "Refiners Re-Cut the Barrel. They Did Not Enlarge It.",
    "publishDate": "2026-08-22",
    "views": 329,
    "subscribersGained": 4,
    "conversionRate": 1.31,
    "topic": "Oil",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "Middle East jet-fuel output ran 640,000 b/d below February from March to June. Refiners elsewhere made up the volume by lifting jet yields. Diesel now outbids jet fuel for those molecules.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 3,
    "comments": 0
  },
  {
    "id": "art-211300130",
    "title": "Permission Moves in a Day. Plant Moves in Years.",
    "publishDate": "2026-08-15",
    "views": 701,
    "subscribersGained": 11,
    "conversionRate": 1.64,
    "topic": "Markets",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "The UAE stopped taking an OPEC quota on May 1. Crude output rose. The next increment of gas processing and fractionation capacity is at investment decision, not in service.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 2
  },
  {
    "id": "art-210734171",
    "title": "The Mine Has Ore. The Plant Still Needs Acid.",
    "publishDate": "2026-08-11",
    "views": 389,
    "subscribersGained": 8,
    "conversionRate": 2.05,
    "topic": "Hard Assets",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "Hormuz turned an already-tight sulfur market acute, and that shock reached an Indonesian nickel plant. The outcome depended on the flowsheet and reagent position, not the metal.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-210029640",
    "title": "A Declaration Is Not Cover.",
    "publishDate": "2026-08-06",
    "views": 509,
    "subscribersGained": 5,
    "conversionRate": 0.99,
    "topic": "Markets",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "Riyadh pledged protection over Bab el-Mandeb, then founded an alliance. Underwriters wrote covenants anyway. The only publicly explained crossings ran on Houthi clearance.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 6,
    "comments": 0
  },
  {
    "id": "art-208820989",
    "title": "Three Negotiations. None of Them With Russia.",
    "publishDate": "2026-07-30",
    "views": 167,
    "subscribersGained": 2,
    "conversionRate": 1.27,
    "topic": "Geopolitics",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "The EU held the Russian oil cap at $44.10 rather than let its formula lift it to $58, and shielded a specialist Greek LNG fleet. Both were settled among Europeans, not with Moscow.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 1,
    "comments": 0
  },
  {
    "id": "art-208181574",
    "title": "The Market Survived on Stored Barrels. The Next One Is a Choice.",
    "publishDate": "2026-07-23",
    "views": 437,
    "subscribersGained": 7,
    "conversionRate": 1.6,
    "topic": "Oil",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "Emergency reserves became recurring supply, not just reassurance. Most of the first authorised release is already drawn. The next stabilising barrel is political, not automatic.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 3
  },
  {
    "id": "art-207896371",
    "title": "Leaving the Strait Is Capacity. Reaching the Buyer Is Resilience.",
    "publishDate": "2026-07-21",
    "views": 891,
    "subscribersGained": 18,
    "conversionRate": 1.97,
    "topic": "Geopolitics",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "The Gulf's routes around Hormuz keep crude flowing — but Fujairah loads into open water, Yanbu escapes one strait into another, and Qatari LNG has no way around it at all.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 3
  },
  {
    "id": "art-207534278",
    "title": "The Barrels Left the Quota. Not the Market.",
    "publishDate": "2026-07-18",
    "views": 328,
    "subscribersGained": 3,
    "conversionRate": 0.92,
    "topic": "Oil",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "The UAE quit OPEC+ on May 1. Its crude did not leave the market — it left the system the alliance uses to restrain supply. OPEC+ can still cut. It cannot discipline Abu Dhabi from inside.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-207267797",
    "title": "The Strait Was Passable. For LNG, That Wasn’t Enough.",
    "publishDate": "2026-07-16",
    "views": 674,
    "subscribersGained": 9,
    "conversionRate": 1.31,
    "topic": "Geopolitics",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "An LNG carrier was struck July 7. Three Qatari ships turned back, and no LNG carrier has crossed since July 11 while other cargo kept moving. A passable Strait, a stalled LNG chain.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 6,
    "comments": 2
  },
  {
    "id": "art-206998467",
    "title": "Announced Gigawatts Are Not Operating Gigawatts.",
    "publishDate": "2026-07-14",
    "views": 510,
    "subscribersGained": 9,
    "conversionRate": 1.67,
    "topic": "AI",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "A one-gigawatt AI campus in Alberta rests on three power layers — a supply contract, a grid allocation, a gas plant years from starting. The headline number is not the deliverable one.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming AI articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming AI articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-206433443",
    "title": "The Crisis Came Through Oil. Gold Priced It as Rates.",
    "publishDate": "2026-07-10",
    "views": 444,
    "subscribersGained": 9,
    "conversionRate": 1.98,
    "topic": "Oil",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "A renewed Iran shock sent oil up more than 5%. That should have lifted gold. It fell nearly 2% as yields and the dollar rose — the tape priced the shock through rates first, not fear.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 3,
    "comments": 0
  },
  {
    "id": "art-206058910",
    "title": "Oil Flinched First. The Bond Market Flinched Too.",
    "publishDate": "2026-07-08",
    "views": 198,
    "subscribersGained": 2,
    "conversionRate": 0.91,
    "topic": "Oil",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "JMIC confirmed three tanker attacks on July 7. OFAC revoked Iran's oil license hours later. Crude moved first — then the 30-year Treasury yield cleared 5% and breakevens ticked higher too.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 1,
    "comments": 0
  },
  {
    "id": "art-205206330",
    "title": "A Smaller Ticket. The Same Barrel.",
    "publishDate": "2026-07-05",
    "views": 467,
    "subscribersGained": 6,
    "conversionRate": 1.3,
    "topic": "Oil",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "CME's new 10-barrel WTI contract is slated for launch on August 30. The crude market underneath it hasn't gotten any easier to trade — only the ticket to bet on it has.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 4,
    "comments": 2
  },
  {
    "id": "art-204396670",
    "title": "Central Banks Kept Buying. Gold Fell Anyway.",
    "publishDate": "2026-07-01",
    "views": 226,
    "subscribersGained": 4,
    "conversionRate": 1.66,
    "topic": "Hard Assets",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "Gold had its worst quarter since 2013 while surveyed central banks expected official reserves to keep rising. Both are true. Reserve demand and the traded price run on different clocks.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-203969094",
    "title": "Hormuz Didn't Reopen. The Tollbooth Moved.",
    "publishDate": "2026-06-28",
    "views": 1233,
    "subscribersGained": 24,
    "conversionRate": 1.94,
    "topic": "Geopolitics",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "The Strait went from closed to argued over. Iran is selling permission. Oman is denying tolls in public and pricing services in private. Hormuz is physically open in places — and priced as if it isn't",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 4,
    "comments": 0
  },
  {
    "id": "art-203392714",
    "title": "The Mine Is Not the Supply",
    "publishDate": "2026-06-26",
    "views": 357,
    "subscribersGained": 3,
    "conversionRate": 0.92,
    "topic": "Hard Assets",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "The DRC replaced its export ban with a quota. The cobalt market is now quoting two prices: the old glut and the new access.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-202686929",
    "title": "The Vault Is the Variable",
    "publishDate": "2026-06-19",
    "views": 265,
    "subscribersGained": 3,
    "conversionRate": 1.29,
    "topic": "Hard Assets",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "Central Banks are repatriating gold,diversifying where it sits, and in some cases mobilizing it under stress. The direction of the flow stopped being the signal. The sovereign's constraint always was.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-202609281",
    "title": "The Rate Didn't Move. The Path Did.",
    "publishDate": "2026-06-18",
    "views": 110,
    "subscribersGained": 2,
    "conversionRate": 1.55,
    "topic": "Macro",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "The Fed held at 3.5–3.75%. But the projected path moved higher, forward guidance disappeared from the statement, and markets had to price a less comfortable future.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Macro articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Macro articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 0,
    "comments": 0
  },
  {
    "id": "art-200991664",
    "title": "Who Pays When Crude Goes Up?",
    "publishDate": "2026-06-07",
    "views": 577,
    "subscribersGained": 12,
    "conversionRate": 2,
    "topic": "Oil",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "The first wave was oil. The second wave was rates. The third wave is in the country tier — and the FX screen is showing it before the credit ratings do.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 2
  },
  {
    "id": "art-199858931",
    "title": "Second Wave. Different Barrel.",
    "publishDate": "2026-05-30",
    "views": 472,
    "subscribersGained": 5,
    "conversionRate": 1,
    "topic": "Oil",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "The first wave was oil. The second wave is rates. The cross-asset map has split — and the dispersion within it tells you where the next move is.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 6,
    "comments": 2
  },
  {
    "id": "art-199729795",
    "title": "The toll booth is still operational",
    "publishDate": "2026-05-29",
    "views": 180,
    "subscribersGained": 2,
    "conversionRate": 1.27,
    "topic": "Geopolitics",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "Even as attacks and counter-strikes escalate, one fact remains unchanged:",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 1,
    "comments": 0
  },
  {
    "id": "art-198939442",
    "title": "The Toll Booth at the Mouth of the World",
    "publishDate": "2026-05-23",
    "views": 255,
    "subscribersGained": 4,
    "conversionRate": 1.64,
    "topic": "Geopolitics",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "Iran built a chokepoint authority. The US tried to escort its way around it. The Saudis declined to help. The scorecard is still 0 out of 5",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 2,
    "comments": 0
  },
  {
    "id": "art-198914118",
    "title": "The Toll Booth at the Mouth of the World",
    "publishDate": "2026-05-23",
    "views": 1140,
    "subscribersGained": 22,
    "conversionRate": 1.93,
    "topic": "Geopolitics",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "Iran built a chokepoint authority. The US tried to escort its way around it. The Saudis declined to help. The scorecard is still 0 out of 5.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 3,
    "comments": 0
  },
  {
    "id": "art-197301647",
    "title": "PSI Capital crossed 100 subscribers on Substack in our first month- Thank you",
    "publishDate": "2026-05-12",
    "views": 257,
    "subscribersGained": 3,
    "conversionRate": 1.08,
    "topic": "Markets",
    "CTAtype": "Subscribe",
    "format": "Scorecard",
    "thesis": "When we started, the goal was simple: build a clearer way to think about how macro and geopolitics flow through commodities, prices, and industries.Thanks for reading PSI Capital's Substack!",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-197088652",
    "title": "The Invoice Has Left the Barrel",
    "publishDate": "2026-05-10",
    "views": 999,
    "subscribersGained": 13,
    "conversionRate": 1.28,
    "topic": "Oil",
    "CTAtype": "Read Post",
    "format": "Essay",
    "thesis": "Four notes. One framework. Oil is staying firm — and the bill is already moving through the system.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 7,
    "comments": 7
  },
  {
    "id": "art-196102130",
    "title": "Who Pays for $110-120 Oil?",
    "publishDate": "2026-05-01",
    "views": 703,
    "subscribersGained": 12,
    "conversionRate": 1.64,
    "topic": "Oil",
    "CTAtype": "Comment",
    "format": "Essay",
    "thesis": "The barrel is where the shock starts. The balance sheet is where it becomes a regime.",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-195332390",
    "title": "The Market Is Still Counting Spare It Cannot Actually Use",
    "publishDate": "2026-04-24",
    "views": 476,
    "subscribersGained": 10,
    "conversionRate": 2.03,
    "topic": "Markets",
    "CTAtype": "Subscribe",
    "format": "Essay",
    "thesis": "Last week's plunge into the mid-$80s was a misread. The cushion is smaller than the market still wants to believe. This article is Part 1 in this series",
    "baselinePerformance": "+15% vs baseline",
    "smmAdvice": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "ctaStrategy": "Mid-article free preview cutoff with an explicit 1-click email capture prompt.",
    "likes": 5,
    "comments": 0
  },
  {
    "id": "art-194532864",
    "title": "The Talks Came Back. The System Still Didn’t.",
    "publishDate": "2026-04-17",
    "views": 939,
    "subscribersGained": 9,
    "conversionRate": 0.98,
    "topic": "Markets",
    "CTAtype": "Restack",
    "format": "Essay",
    "thesis": "The market keeps pricing relief before the corridor proves it should. Three headlines in ten days. The same mismatch every time.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 10,
    "comments": 4
  },
  {
    "id": "art-193936421",
    "title": "The Market Priced Peace. The Oil System Didn’t.",
    "publishDate": "2026-04-12",
    "views": 717,
    "subscribersGained": 9,
    "conversionRate": 1.28,
    "topic": "Oil",
    "CTAtype": "Reply",
    "format": "Essay",
    "thesis": "A ceasefire removed immediate panic. It did not restore the route, the insurers, the operators, or the physical market underneath it.",
    "baselinePerformance": "-35% conversion velocity (CTA opportunity)",
    "smmAdvice": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "ctaStrategy": "Inline Callout Box: \"Join 12,000+ institutional macro allocators receiving our private updates.\"",
    "likes": 5,
    "comments": 1
  }
];

export const MOCK_NOTES: SubstackNote[] = [
  {
    "id": "note-324233258",
    "hook": "The roadstead has room. The constraint is narrower: how many owners will keep sending a shuttle across Hormuz, again and again, wh...",
    "publishDate": "2026-08-29",
    "impressions": 292,
    "likes": 4,
    "restacks": 2,
    "replies": 0,
    "profileClicks": 15,
    "subscribersGained": 2,
    "format": "Chart",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 15 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-324232985",
    "hook": "Watch the transfer zone and the system looks busy. Watch which hull crosses Hormuz and which doesn't, and the picture changes.  On...",
    "publishDate": "2026-08-28",
    "impressions": 210,
    "likes": 5,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 14,
    "subscribersGained": 2,
    "format": "Image",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 14 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-324232726",
    "hook": "A large number of barrels sitting in ship-to-ship pairs is not the same as a restored daily flow through the Strait. Stock in tran...",
    "publishDate": "2026-08-28",
    "impressions": 182,
    "likes": 4,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 15,
    "subscribersGained": 2,
    "format": "Chart",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-323702181",
    "hook": "Millions of barrels are still leaving Hormuz. That sentence is true. It is also incomplete. The catch is not whether oil is moving...",
    "publishDate": "2026-08-27",
    "impressions": 321,
    "likes": 7,
    "restacks": 1,
    "replies": 0,
    "profileClicks": 30,
    "subscribersGained": 4,
    "format": "Text",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 30 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-323667919",
    "hook": "Later today: our read on the Hormuz STS relay. The transfer zone has room. The shuttle fleet is what's being squeezed — by Iran on...",
    "publishDate": "2026-08-27",
    "impressions": 182,
    "likes": 4,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 9,
    "subscribersGained": 1,
    "format": "Text",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-323583425",
    "hook": "The CFTC extended the review period of CME’s 10 barrel WTI contract through to October 26, 2026 for the same concerns we had expre...",
    "publishDate": "2026-08-27",
    "impressions": 174,
    "likes": 3,
    "restacks": 0,
    "replies": 1,
    "profileClicks": 11,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-212292339",
    "topic": "Oil",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-323235591",
    "hook": "If you want to understand how the catastrophe in Nepal could have happened, I published an article a month ago about how rivers an...",
    "publishDate": "2026-08-26",
    "impressions": 313,
    "likes": 6,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 25,
    "subscribersGained": 3,
    "format": "Chart",
    "linkedArticleId": "art-211300130",
    "topic": "Markets",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 25 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-322878081",
    "hook": "Iran’s Army is now claiming a wider control zone, not just the Strait.  It says vessels are under surveillance hundreds of kilomet...",
    "publishDate": "2026-08-26",
    "impressions": 209,
    "likes": 3,
    "restacks": 1,
    "replies": 0,
    "profileClicks": 20,
    "subscribersGained": 2,
    "format": "Image",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-322333133",
    "hook": "Ship operators face two sets of instructions that do not resolve into one workable rule. Iran has struck vessels that left its des...",
    "publishDate": "2026-08-25",
    "impressions": 285,
    "likes": 5,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 14,
    "subscribersGained": 2,
    "format": "Chart",
    "linkedArticleId": "art-211300130",
    "topic": "Markets",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 14 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-322149592",
    "hook": "The U.S. Treasury is now warning that sailors and shipping companies can risk sanctions or penalties simply by responding to infor...",
    "publishDate": "2026-08-25",
    "impressions": 201,
    "likes": 2,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 13,
    "subscribersGained": 2,
    "format": "Text",
    "linkedArticleId": "art-206998467",
    "topic": "AI",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-322043197",
    "hook": "One source this week claimed the U.S. has only 41 days of crude left — the lowest cover in half a century.  That figure folds comm...",
    "publishDate": "2026-08-25",
    "impressions": 154,
    "likes": 3,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 12,
    "subscribersGained": 1,
    "format": "Chart",
    "linkedArticleId": "art-212292339",
    "topic": "Oil",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-321644418",
    "hook": "The problem is that lower long-term yields are not a free lunch. If Treasury pushes them down through buybacks while deficits rema...",
    "publishDate": "2026-08-24",
    "impressions": 258,
    "likes": 6,
    "restacks": 0,
    "replies": 1,
    "profileClicks": 25,
    "subscribersGained": 3,
    "format": "Text",
    "linkedArticleId": "art-202609281",
    "topic": "Macro",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 25 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-321349458",
    "hook": "FT reports that Saudi Arabia is evaluating state-backed war insurance as private cover costs remain elevated.  State-backed cover ...",
    "publishDate": "2026-08-24",
    "impressions": 405,
    "likes": 10,
    "restacks": 1,
    "replies": 0,
    "profileClicks": 20,
    "subscribersGained": 2,
    "format": "Text",
    "linkedArticleId": "art-206998467",
    "topic": "AI",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 20 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-321490576",
    "hook": "The system is reoptimizing, but by creating scarcity somewhere else rather than absorbing the shock. We wrote about this: “For any...",
    "publishDate": "2026-08-24",
    "impressions": 182,
    "likes": 4,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 12,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-211300130",
    "topic": "Markets",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-321353394",
    "hook": "Headlines moved fast: Buffalo Niagara International Airport out of fuel, unable to refuel aircraft, NOTAM issued. Many reactions t...",
    "publishDate": "2026-08-24",
    "impressions": 229,
    "likes": 3,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 18,
    "subscribersGained": 2,
    "format": "Chart",
    "linkedArticleId": "art-206998467",
    "topic": "AI",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-321344037",
    "hook": "An excellent point:",
    "publishDate": "2026-08-24",
    "impressions": 126,
    "likes": 2,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 12,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-211300130",
    "topic": "Markets",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-321343074",
    "hook": "Iran is building a formal blacklist for ships that break its prescribed transit rules in the Strait of Hormuz. Non-compliant vesse...",
    "publishDate": "2026-08-24",
    "impressions": 229,
    "likes": 3,
    "restacks": 1,
    "replies": 1,
    "profileClicks": 11,
    "subscribersGained": 1,
    "format": "Text",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-320689338",
    "hook": "Most of the replacement jet fuel came from a yield decision, not from new capacity. We explain why:",
    "publishDate": "2026-08-23",
    "impressions": 154,
    "likes": 3,
    "restacks": 0,
    "replies": 0,
    "profileClicks": 10,
    "subscribersGained": 1,
    "format": "Image",
    "linkedArticleId": "art-212292339",
    "topic": "Oil",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  },
  {
    "id": "note-320281056",
    "hook": "The jet-fuel emergency has closed as a shortage story. It has reopened as an allocation one.  We explain why:",
    "publishDate": "2026-08-22",
    "impressions": 376,
    "likes": 7,
    "restacks": 2,
    "replies": 0,
    "profileClicks": 30,
    "subscribersGained": 4,
    "format": "Chart",
    "linkedArticleId": "art-212292339",
    "topic": "Oil",
    "hookAnalysis": "High-performing hook. The contrarian assertion created strong intrigue, driving 30 profile visits and organic restacks.",
    "futureNoteAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%."
  },
  {
    "id": "note-320130842",
    "hook": "Iran has granted special permission for a number of Iraqi oil tankers to transit the Strait of Hormuz — after repeated requests fr...",
    "publishDate": "2026-08-22",
    "impressions": 209,
    "likes": 3,
    "restacks": 1,
    "replies": 0,
    "profileClicks": 20,
    "subscribersGained": 2,
    "format": "Image",
    "linkedArticleId": "art-212972059",
    "topic": "Geopolitics",
    "hookAnalysis": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "futureNoteAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context."
  }
];

export const MOCK_SMM_DIAGNOSTICS: SMMDiagnostic[] = [
  {
    "id": "diag-art-1",
    "contentTitle": "Millions of Barrels Are Still Getting Out of Hormuz. Here's the Catch.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 480 views. Conversion rate sits at 0.97%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "480 Views | 0.97% Conv."
  },
  {
    "id": "diag-art-2",
    "contentTitle": "Refiners Re-Cut the Barrel. They Did Not Enlarge It.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 329 views. Conversion rate sits at 1.31%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "329 Views | 1.31% Conv."
  },
  {
    "id": "diag-art-3",
    "contentTitle": "Permission Moves in a Day. Plant Moves in Years.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Markets",
    "theWhy": "Steady engagement with 701 views. Conversion rate sits at 1.64%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "701 Views | 1.64% Conv."
  },
  {
    "id": "diag-art-4",
    "contentTitle": "The Mine Has Ore. The Plant Still Needs Acid.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Hard Assets",
    "theWhy": "Steady engagement with 389 views. Conversion rate sits at 2.05%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "389 Views | 2.05% Conv."
  },
  {
    "id": "diag-art-5",
    "contentTitle": "A Declaration Is Not Cover.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Markets",
    "theWhy": "Steady engagement with 509 views. Conversion rate sits at 0.99%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "509 Views | 0.99% Conv."
  },
  {
    "id": "diag-art-6",
    "contentTitle": "Three Negotiations. None of Them With Russia.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 167 views. Conversion rate sits at 1.27%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "167 Views | 1.27% Conv."
  },
  {
    "id": "diag-art-7",
    "contentTitle": "The Market Survived on Stored Barrels. The Next One Is a Choice.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 437 views. Conversion rate sits at 1.6%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "437 Views | 1.6% Conv."
  },
  {
    "id": "diag-art-8",
    "contentTitle": "Leaving the Strait Is Capacity. Reaching the Buyer Is Resilience.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 891 views. Conversion rate sits at 1.97%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "891 Views | 1.97% Conv."
  },
  {
    "id": "diag-art-9",
    "contentTitle": "The Barrels Left the Quota. Not the Market.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 328 views. Conversion rate sits at 0.92%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "328 Views | 0.92% Conv."
  },
  {
    "id": "diag-art-10",
    "contentTitle": "The Strait Was Passable. For LNG, That Wasn’t Enough.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 674 views. Conversion rate sits at 1.31%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "674 Views | 1.31% Conv."
  },
  {
    "id": "diag-art-11",
    "contentTitle": "Announced Gigawatts Are Not Operating Gigawatts.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "AI",
    "theWhy": "Steady engagement with 510 views. Conversion rate sits at 1.67%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming AI articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "510 Views | 1.67% Conv."
  },
  {
    "id": "diag-art-12",
    "contentTitle": "The Crisis Came Through Oil. Gold Priced It as Rates.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 444 views. Conversion rate sits at 1.98%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "444 Views | 1.98% Conv."
  },
  {
    "id": "diag-art-13",
    "contentTitle": "Oil Flinched First. The Bond Market Flinched Too.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 198 views. Conversion rate sits at 0.91%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "198 Views | 0.91% Conv."
  },
  {
    "id": "diag-art-14",
    "contentTitle": "A Smaller Ticket. The Same Barrel.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 467 views. Conversion rate sits at 1.3%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "467 Views | 1.3% Conv."
  },
  {
    "id": "diag-art-15",
    "contentTitle": "Central Banks Kept Buying. Gold Fell Anyway.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Hard Assets",
    "theWhy": "Steady engagement with 226 views. Conversion rate sits at 1.66%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Hard Assets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "226 Views | 1.66% Conv."
  },
  {
    "id": "diag-art-16",
    "contentTitle": "Hormuz Didn't Reopen. The Tollbooth Moved.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 1,233 views. Conversion rate sits at 1.94%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "1,233 Views | 1.94% Conv."
  },
  {
    "id": "diag-art-17",
    "contentTitle": "The Mine Is Not the Supply",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Hard Assets",
    "theWhy": "Steady engagement with 357 views. Conversion rate sits at 0.92%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "357 Views | 0.92% Conv."
  },
  {
    "id": "diag-art-18",
    "contentTitle": "The Vault Is the Variable",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Hard Assets",
    "theWhy": "Steady engagement with 265 views. Conversion rate sits at 1.29%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "265 Views | 1.29% Conv."
  },
  {
    "id": "diag-art-19",
    "contentTitle": "The Rate Didn't Move. The Path Did.",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Macro",
    "theWhy": "Steady engagement with 110 views. Conversion rate sits at 1.55%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Macro articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "110 Views | 1.55% Conv."
  },
  {
    "id": "diag-art-20",
    "contentTitle": "Who Pays When Crude Goes Up?",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 577 views. Conversion rate sits at 2%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "577 Views | 2% Conv."
  },
  {
    "id": "diag-art-21",
    "contentTitle": "Second Wave. Different Barrel.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 472 views. Conversion rate sits at 1%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "472 Views | 1% Conv."
  },
  {
    "id": "diag-art-22",
    "contentTitle": "The toll booth is still operational",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 180 views. Conversion rate sits at 1.27%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "180 Views | 1.27% Conv."
  },
  {
    "id": "diag-art-23",
    "contentTitle": "The Toll Booth at the Mouth of the World",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 255 views. Conversion rate sits at 1.64%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "255 Views | 1.64% Conv."
  },
  {
    "id": "diag-art-24",
    "contentTitle": "The Toll Booth at the Mouth of the World",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Geopolitics",
    "theWhy": "Steady engagement with 1,140 views. Conversion rate sits at 1.93%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Geopolitics articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "1,140 Views | 1.93% Conv."
  },
  {
    "id": "diag-art-25",
    "contentTitle": "PSI Capital crossed 100 subscribers on Substack in our first month- Thank you",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Scorecard",
    "topic": "Markets",
    "theWhy": "Steady engagement with 257 views. Conversion rate sits at 1.08%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "257 Views | 1.08% Conv."
  },
  {
    "id": "diag-art-26",
    "contentTitle": "The Invoice Has Left the Barrel",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 999 views. Conversion rate sits at 1.28%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "999 Views | 1.28% Conv."
  },
  {
    "id": "diag-art-27",
    "contentTitle": "Who Pays for $110-120 Oil?",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 703 views. Conversion rate sits at 1.64%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Oil articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "703 Views | 1.64% Conv."
  },
  {
    "id": "diag-art-28",
    "contentTitle": "The Market Is Still Counting Spare It Cannot Actually Use",
    "contentType": "Article",
    "diagnosticType": "CTA Opportunity",
    "articleType": "Essay",
    "topic": "Markets",
    "theWhy": "Steady engagement with 476 views. Conversion rate sits at 2.03%.",
    "frictionPoint": "CTA button was placed below technical data tables where reader drop-off occurs.",
    "futureAction": "For upcoming Markets articles: Move the primary value proposition to 40% scroll depth and offer a clear free-tier teaser before technical appendices.",
    "metricHighlight": "476 Views | 2.03% Conv."
  },
  {
    "id": "diag-art-29",
    "contentTitle": "The Talks Came Back. The System Still Didn’t.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Markets",
    "theWhy": "Steady engagement with 939 views. Conversion rate sits at 0.98%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "939 Views | 0.98% Conv."
  },
  {
    "id": "diag-art-30",
    "contentTitle": "The Market Priced Peace. The Oil System Didn’t.",
    "contentType": "Article",
    "diagnosticType": "Low Engagement",
    "articleType": "Essay",
    "topic": "Oil",
    "theWhy": "Steady engagement with 717 views. Conversion rate sits at 1.28%.",
    "frictionPoint": "Readers consumed the summary without feeling urgency to subscribe for ongoing coverage.",
    "futureAction": "Tighten the analytical focus on immediate trade/market implications. Include a bolded \"What Institutional Investors Must Watch Next\" section with a dedicated subscribe lock.",
    "metricHighlight": "717 Views | 1.28% Conv."
  },
  {
    "id": "diag-note-1",
    "contentTitle": "Note: \"The roadstead has room. The constraint is narrower...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Chart",
    "topic": "Geopolitics",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 15 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 5.1% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "4 Likes | 2 Restacks"
  },
  {
    "id": "diag-note-2",
    "contentTitle": "Note: \"Watch the transfer zone and the system looks busy....\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Image",
    "topic": "Geopolitics",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 14 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 6.7% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "5 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-3",
    "contentTitle": "Note: \"A large number of barrels sitting in ship-to-ship ...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Chart",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 8.2% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "4 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-4",
    "contentTitle": "Note: \"Millions of barrels are still leaving Hormuz. That...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Text",
    "topic": "Geopolitics",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 30 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 9.3% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "7 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-5",
    "contentTitle": "Note: \"Later today: our read on the Hormuz STS relay. The...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Text",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 4.9% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "4 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-6",
    "contentTitle": "Note: \"The CFTC extended the review period of CME’s 10 ba...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Oil",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 6.3% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-7",
    "contentTitle": "Note: \"If you want to understand how the catastrophe in N...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Chart",
    "topic": "Markets",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 25 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 8.0% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "6 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-8",
    "contentTitle": "Note: \"Iran’s Army is now claiming a wider control zone, ...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 9.6% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-9",
    "contentTitle": "Note: \"Ship operators face two sets of instructions that ...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Chart",
    "topic": "Markets",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 14 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 4.9% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "5 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-10",
    "contentTitle": "Note: \"The U.S. Treasury is now warning that sailors and ...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Text",
    "topic": "AI",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 6.5% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "2 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-11",
    "contentTitle": "Note: \"One source this week claimed the U.S. has only 41 ...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Chart",
    "topic": "Oil",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 7.8% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-12",
    "contentTitle": "Note: \"The problem is that lower long-term yields are not...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Text",
    "topic": "Macro",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 25 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 9.7% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "6 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-13",
    "contentTitle": "Note: \"FT reports that Saudi Arabia is evaluating state-b...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Text",
    "topic": "AI",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 20 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 4.9% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "10 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-14",
    "contentTitle": "Note: \"The system is reoptimizing, but by creating scarci...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Markets",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 6.6% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "4 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-15",
    "contentTitle": "Note: \"Headlines moved fast: Buffalo Niagara Internationa...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Chart",
    "topic": "AI",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 7.9% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-16",
    "contentTitle": "Note: \"An excellent point:...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Markets",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 9.5% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "2 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-17",
    "contentTitle": "Note: \"Iran is building a formal blacklist for ships that...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Text",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 4.8% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 1 Restacks"
  },
  {
    "id": "diag-note-18",
    "contentTitle": "Note: \"Most of the replacement jet fuel came from a yield...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Oil",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 6.5% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 0 Restacks"
  },
  {
    "id": "diag-note-19",
    "contentTitle": "Note: \"The jet-fuel emergency has closed as a shortage st...\"",
    "contentType": "Note",
    "diagnosticType": "High Conversion",
    "noteType": "Chart",
    "topic": "Oil",
    "theWhy": "High-performing hook. The contrarian assertion created strong intrigue, driving 30 profile visits and organic restacks.",
    "frictionPoint": "Profile CTR generated 8.0% conversion to creator bio.",
    "futureAction": "Re-use this punchy 2-sentence format. Pair with a high-contrast infographic chart within 60 minutes of publication to lift restacks by ~35%.",
    "metricHighlight": "7 Likes | 2 Restacks"
  },
  {
    "id": "diag-note-20",
    "contentTitle": "Note: \"Iran has granted special permission for a number o...\"",
    "contentType": "Note",
    "diagnosticType": "CTA Opportunity",
    "noteType": "Image",
    "topic": "Geopolitics",
    "theWhy": "Moderate engagement. The opening line provides informative context but lacks a sharp tension or provocative counter-consensus statement.",
    "frictionPoint": "Profile CTR generated 9.6% conversion to creator bio.",
    "futureAction": "Next Note: Lead with a quantitative surprise (e.g. \"41 days of inventory remaining...\") rather than broad narrative context.",
    "metricHighlight": "3 Likes | 1 Restacks"
  }
];

export const MOCK_TRAFFIC_SOURCES: TrafficSourceItem[] = [
  {
    id: 'ts-01',
    source: 'Substack App & Recommendations',
    category: 'Substack Internal',
    uniqueVisitors: 18500,
    newSubscribers: 980,
    conversionRate: 5.30,
    qualityClassification: 'High',
    description: 'Readers discovering your publication inside the Substack mobile app, recommendation algorithm, and cross-writer suggestions.'
  },
  {
    id: 'ts-02',
    source: 'Google Search / SEO',
    category: 'Organic Search',
    uniqueVisitors: 12400,
    newSubscribers: 434,
    conversionRate: 3.50,
    qualityClassification: 'Medium',
    description: 'Organic search traffic landing directly on long-form essays via Google, Bing, and DuckDuckGo.'
  },
  {
    id: 'ts-03',
    source: 'Twitter / X Shares',
    category: 'Social Media',
    uniqueVisitors: 15200,
    newSubscribers: 380,
    conversionRate: 2.50,
    qualityClassification: 'Medium',
    description: 'Viral thread links and article shares posted on Twitter/X.'
  },
  {
    id: 'ts-04',
    source: 'LinkedIn Posts & Pulse',
    category: 'Social Media',
    uniqueVisitors: 6100,
    newSubscribers: 286,
    conversionRate: 4.69,
    qualityClassification: 'Medium',
    description: 'Executive and institutional reader clicks from professional LinkedIn posts.'
  },
  {
    id: 'ts-05',
    source: 'Direct / Unattributed',
    category: 'Direct / Unattributed',
    uniqueVisitors: 9800,
    newSubscribers: 117,
    conversionRate: 1.19,
    qualityClassification: 'Low',
    description: 'Traffic where available Substack analytics headers omit referrer details (e.g. mobile mail apps, private browser tabs, bookmarks, or instant message apps).'
  },
  {
    id: 'ts-06',
    source: 'Financial Blogs & News aggregators',
    category: 'Other External',
    uniqueVisitors: 4200,
    newSubscribers: 189,
    conversionRate: 4.50,
    qualityClassification: 'Medium',
    description: 'Backlinks from external market commentary sites like SeekingAlpha and RealClearMarkets.'
  }
];

export const MOCK_TIME_SERIES = {
  'Last 7 Days': [
    { date: 'Aug 25', subscribers: 12410, organicSubscribers: 42, referralSubscribers: 18 },
    { date: 'Aug 26', subscribers: 12475, organicSubscribers: 48, referralSubscribers: 17 },
    { date: 'Aug 27', subscribers: 12540, organicSubscribers: 45, referralSubscribers: 20 },
    { date: 'Aug 28', subscribers: 12620, organicSubscribers: 55, referralSubscribers: 25 },
    { date: 'Aug 29', subscribers: 12780, organicSubscribers: 110, referralSubscribers: 50 },
    { date: 'Aug 30', subscribers: 12890, organicSubscribers: 80, referralSubscribers: 30 },
    { date: 'Aug 31', subscribers: 12968, organicSubscribers: 52, referralSubscribers: 26 },
  ],
  'Last 30 Days': Array.from({ length: 30 }, (_, i) => {
    const day = i + 1;
    const baseSubs = 11200 + i * 58 + Math.floor(Math.sin(i) * 30);
    return {
      date: `Aug ${day}`,
      subscribers: baseSubs,
      organicSubscribers: 35 + Math.floor(Math.random() * 25),
      referralSubscribers: 15 + Math.floor(Math.random() * 15),
    };
  }),
  'Last 90 Days': [
    { date: 'Wk 1 (Jun)', subscribers: 9800, organicSubscribers: 210, referralSubscribers: 95 },
    { date: 'Wk 2 (Jun)', subscribers: 10120, organicSubscribers: 220, referralSubscribers: 100 },
    { date: 'Wk 3 (Jun)', subscribers: 10450, organicSubscribers: 240, referralSubscribers: 90 },
    { date: 'Wk 4 (Jun)', subscribers: 10780, organicSubscribers: 230, referralSubscribers: 100 },
    { date: 'Wk 5 (Jul)', subscribers: 11100, organicSubscribers: 225, referralSubscribers: 95 },
    { date: 'Wk 6 (Jul)', subscribers: 11520, organicSubscribers: 310, referralSubscribers: 110 },
    { date: 'Wk 7 (Jul)', subscribers: 11980, organicSubscribers: 330, referralSubscribers: 130 },
    { date: 'Wk 8 (Jul)', subscribers: 12250, organicSubscribers: 190, referralSubscribers: 80 },
    { date: 'Wk 9 (Aug)', subscribers: 12480, organicSubscribers: 160, referralSubscribers: 70 },
    { date: 'Wk 10 (Aug)', subscribers: 12620, organicSubscribers: 100, referralSubscribers: 40 },
    { date: 'Wk 11 (Aug)', subscribers: 12850, organicSubscribers: 160, referralSubscribers: 70 },
    { date: 'Wk 12 (Aug)', subscribers: 12968, organicSubscribers: 82, referralSubscribers: 36 },
  ],
  'All-Time': [
    { date: 'Apr 2026', subscribers: 4200, organicSubscribers: 600, referralSubscribers: 200 },
    { date: 'May 2026', subscribers: 6800, organicSubscribers: 950, referralSubscribers: 350 },
    { date: 'Jun 2026', subscribers: 9100, organicSubscribers: 1200, referralSubscribers: 400 },
    { date: 'Jul 2026', subscribers: 11200, organicSubscribers: 1300, referralSubscribers: 400 },
    { date: 'Aug 2026', subscribers: 12968, organicSubscribers: 1500, referralSubscribers: 480 },
  ]
};
